//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials.
        /// </summary>
        public static string Access_denied {
            get {
                return ResourceManager.GetString("Access_denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated.
        /// </summary>
        public static string Activated {
            get {
                return ResourceManager.GetString("Activated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License activation code.
        /// </summary>
        public static string ActivationCode {
            get {
                return ResourceManager.GetString("ActivationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an answer option.
        /// </summary>
        public static string Add_Answer {
            get {
                return ResourceManager.GetString("Add_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a group of questionnaires.
        /// </summary>
        public static string Add_Group_Questionnaire {
            get {
                return ResourceManager.GetString("Add_Group_Questionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a questionnaire.
        /// </summary>
        public static string Add_GroupQuestion {
            get {
                return ResourceManager.GetString("Add_GroupQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate licenses.
        /// </summary>
        public static string Add_Lincense {
            get {
                return ResourceManager.GetString("Add_Lincense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add question.
        /// </summary>
        public static string Add_Question {
            get {
                return ResourceManager.GetString("Add_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved..
        /// </summary>
        public static string AllRightsReserved {
            get {
                return ResourceManager.GetString("AllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible answer.
        /// </summary>
        public static string Answert_Response {
            get {
                return ResourceManager.GetString("Answert_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply data.
        /// </summary>
        public static string Apply_data_Statistica {
            get {
                return ResourceManager.GetString("Apply_data_Statistica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request approved.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization.
        /// </summary>
        public static string Authorization {
            get {
                return ResourceManager.GetString("Authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be empty..
        /// </summary>
        public static string Cannot_empty {
            get {
                return ResourceManager.GetString("Cannot_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change status.
        /// </summary>
        public static string Change_status {
            get {
                return ResourceManager.GetString("Change_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentary.
        /// </summary>
        public static string Comentary {
            get {
                return ResourceManager.GetString("Comentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password does not match new password.
        /// </summary>
        public static string Confirm_password_not_match {
            get {
                return ResourceManager.GetString("Confirm_password_not match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact administrator.
        /// </summary>
        public static string ContactAdministrator {
            get {
                return ResourceManager.GetString("ContactAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create date.
        /// </summary>
        public static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivated.
        /// </summary>
        public static string Deactivated {
            get {
                return ResourceManager.GetString("Deactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request for _ rejected.
        /// </summary>
        public static string Declined {
            get {
                return ResourceManager.GetString("Declined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delet {
            get {
                return ResourceManager.GetString("Delet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the group:.
        /// </summary>
        public static string Delet_Group_Questionnaire {
            get {
                return ResourceManager.GetString("Delet_Group_Questionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the survey:.
        /// </summary>
        public static string Delet_Questionnaire {
            get {
                return ResourceManager.GetString("Delet_Questionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the question text above to confirm deletion.
        /// </summary>
        public static string Deletion_Сonfirmation {
            get {
                return ResourceManager.GetString("Deletion_Сonfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device name.
        /// </summary>
        public static string Device_Name {
            get {
                return ResourceManager.GetString("Device_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password to unlock your screen!.
        /// </summary>
        public static string Enter_password_unlock_screen {
            get {
                return ResourceManager.GetString("Enter_password_unlock_screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your question....
        /// </summary>
        public static string Enter_Question {
            get {
                return ResourceManager.GetString("Enter_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a comment for the question....
        /// </summary>
        public static string Enter_Сomment {
            get {
                return ResourceManager.GetString("Enter_Сomment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deleting _ data.
        /// </summary>
        public static string Exception_DELETE {
            get {
                return ResourceManager.GetString("Exception_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to receiving _ data.
        /// </summary>
        public static string Exception_GET {
            get {
                return ResourceManager.GetString("Exception_GET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to questionnaire group.
        /// </summary>
        public static string Exception_GroupQuestionnarei {
            get {
                return ResourceManager.GetString("Exception_GroupQuestionnarei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to license.
        /// </summary>
        public static string Exception_Lincense {
            get {
                return ResourceManager.GetString("Exception_Lincense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to questionnaire.
        /// </summary>
        public static string Exception_Oprostnik {
            get {
                return ResourceManager.GetString("Exception_Oprostnik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sending _ data.
        /// </summary>
        public static string Exception_POST {
            get {
                return ResourceManager.GetString("Exception_POST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user profile.
        /// </summary>
        public static string Exception_ProfileInfo {
            get {
                return ResourceManager.GetString("Exception_ProfileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updating _ data.
        /// </summary>
        public static string Exception_PUT {
            get {
                return ResourceManager.GetString("Exception_PUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to question.
        /// </summary>
        public static string Exception_Question {
            get {
                return ResourceManager.GetString("Exception_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation to _ failed.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load survey names..
        /// </summary>
        public static string Failed_load_questionnaire_names {
            get {
                return ResourceManager.GetString("Failed_load_questionnaire_names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field must not be empty.
        /// </summary>
        public static string Field_not_empty {
            get {
                return ResourceManager.GetString("Field_not_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string Forgot_password {
            get {
                return ResourceManager.GetString("Forgot_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Further.
        /// </summary>
        public static string Further {
            get {
                return ResourceManager.GetString("Further", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question type.
        /// </summary>
        public static string GradingType {
            get {
                return ResourceManager.GetString("GradingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionnaire group.
        /// </summary>
        public static string Group_Questionnaire {
            get {
                return ResourceManager.GetString("Group_Questionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionnaire group ID.
        /// </summary>
        public static string GroupQuestionnarie_ID {
            get {
                return ResourceManager.GetString("GroupQuestionnarie_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Error while _.
        /// </summary>
        public static string Internal_error {
            get {
                return ResourceManager.GetString("Internal_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid old password.
        /// </summary>
        public static string Invalid_old_password {
            get {
                return ResourceManager.GetString("Invalid_old_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Token while _.
        /// </summary>
        public static string Invalid_token {
            get {
                return ResourceManager.GetString("Invalid_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Oid of the license above.
        /// </summary>
        public static string Label_Change_Status {
            get {
                return ResourceManager.GetString("Label_Change_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License removed.
        /// </summary>
        public static string License_removed {
            get {
                return ResourceManager.GetString("License_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses created successfully.
        /// </summary>
        public static string Licenses_created {
            get {
                return ResourceManager.GetString("Licenses_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        public static string Lincense {
            get {
                return ResourceManager.GetString("Lincense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation date.
        /// </summary>
        public static string LincenseActivated {
            get {
                return ResourceManager.GetString("LincenseActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of answer options.
        /// </summary>
        public static string List_Answer {
            get {
                return ResourceManager.GetString("List_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Screen.
        /// </summary>
        public static string LockScreen {
            get {
                return ResourceManager.GetString("LockScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not you? Return to page.
        /// </summary>
        public static string LockScreenFooter {
            get {
                return ResourceManager.GetString("LockScreenFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum password length - 8 characters.
        /// </summary>
        public static string Minimum_password_length {
            get {
                return ResourceManager.GetString("Minimum_password_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple answer variant.
        /// </summary>
        public static string MultipleAnswerVariant {
            get {
                return ResourceManager.GetString("MultipleAnswerVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name group.
        /// </summary>
        public static string Name_Group {
            get {
                return ResourceManager.GetString("Name_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the full name of the survey group.
        /// </summary>
        public static string Name_Group_Questionnaire_Delet {
            get {
                return ResourceManager.GetString("Name_Group_Questionnaire_Delet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License name.
        /// </summary>
        public static string Name_Lincense {
            get {
                return ResourceManager.GetString("Name_Lincense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionnaire name.
        /// </summary>
        public static string Name_Questionnaire {
            get {
                return ResourceManager.GetString("Name_Questionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the full name of the surveyor.
        /// </summary>
        public static string Name_Questionnaire_Delet {
            get {
                return ResourceManager.GetString("Name_Questionnaire_Delet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password must not be empty.
        /// </summary>
        public static string New_Password_not_emty {
            get {
                return ResourceManager.GetString("New_Password_not_emty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not activated.
        /// </summary>
        public static string NotActivated {
            get {
                return ResourceManager.GetString("NotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionnaire group oid.
        /// </summary>
        public static string Oid_Grup_Questionnaire {
            get {
                return ResourceManager.GetString("Oid_Grup_Questionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter license Oid.
        /// </summary>
        public static string Oid_Lincense {
            get {
                return ResourceManager.GetString("Oid_Lincense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to removed.
        /// </summary>
        public static string Ok_DELETE {
            get {
                return ResourceManager.GetString("Ok_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionnaire.
        /// </summary>
        public static string Ok_GroupQuestionnarei {
            get {
                return ResourceManager.GetString("Ok_GroupQuestionnarei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string Ok_Lincense {
            get {
                return ResourceManager.GetString("Ok_Lincense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionnaire.
        /// </summary>
        public static string Ok_Oprostnik {
            get {
                return ResourceManager.GetString("Ok_Oprostnik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to added.
        /// </summary>
        public static string Ok_POST {
            get {
                return ResourceManager.GetString("Ok_POST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updated.
        /// </summary>
        public static string Ok_PUT {
            get {
                return ResourceManager.GetString("Ok_PUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Ok_Question {
            get {
                return ResourceManager.GetString("Ok_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to successfully.
        /// </summary>
        public static string Ok_Success {
            get {
                return ResourceManager.GetString("Ok_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The old password must not be empty.
        /// </summary>
        public static string Old_password_not_empty {
            get {
                return ResourceManager.GetString("Old_password_not_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully.
        /// </summary>
        public static string Password_changed_successfully {
            get {
                return ResourceManager.GetString("Password_changed_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must contain both letters, numbers and at least one uppercase letter and symbol.
        /// </summary>
        public static string Password_letters_numbers_capitalletter {
            get {
                return ResourceManager.GetString("Password_letters_numbers_capitalletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password recovery.
        /// </summary>
        public static string Password_recovery {
            get {
                return ResourceManager.GetString("Password_recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10-point rating system.
        /// </summary>
        public static string Point10Score {
            get {
                return ResourceManager.GetString("Point10Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5-point rating system.
        /// </summary>
        public static string Point5Score {
            get {
                return ResourceManager.GetString("Point5Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user profile.
        /// </summary>
        public static string ProfileInfo {
            get {
                return ResourceManager.GetString("ProfileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of licenses.
        /// </summary>
        public static string Quantity_Lincense {
            get {
                return ResourceManager.GetString("Quantity_Lincense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question name to delete.
        /// </summary>
        public static string Question_Delet {
            get {
                return ResourceManager.GetString("Question_Delet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The question has not been created in the current language.
        /// </summary>
        public static string Question_Missing_Lang {
            get {
                return ResourceManager.GetString("Question_Missing_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionnaire.
        /// </summary>
        public static string Questionnaire {
            get {
                return ResourceManager.GetString("Questionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of questionnaires.
        /// </summary>
        public static string Questionnaries_list {
            get {
                return ResourceManager.GetString("Questionnaries_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry _ does not exist.
        /// </summary>
        public static string Record_not_exist {
            get {
                return ResourceManager.GetString("Record_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License release.
        /// </summary>
        public static string Release_button {
            get {
                return ResourceManager.GetString("Release_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License release.
        /// </summary>
        public static string ReleaseLicense {
            get {
                return ResourceManager.GetString("ReleaseLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset.
        /// </summary>
        public static string Reset_Password {
            get {
                return ResourceManager.GetString("Reset_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the email address used for your registration..
        /// </summary>
        public static string ResetPasswordHeader {
            get {
                return ResourceManager.GetString("ResetPasswordHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Panel.
        /// </summary>
        public static string SearchPanel {
            get {
                return ResourceManager.GetString("SearchPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select questionnaires.
        /// </summary>
        public static string Select_Questionnaires {
            get {
                return ResourceManager.GetString("Select_Questionnaires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single answer variant.
        /// </summary>
        public static string SingleAnswerVariant {
            get {
                return ResourceManager.GetString("SingleAnswerVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question _ successfully added/updated. But there were errors when displaying it..
        /// </summary>
        public static string Success_Post_Error_Get {
            get {
                return ResourceManager.GetString("Success_Post_Error_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change license status:.
        /// </summary>
        public static string Text_Change_Status_Lincense {
            get {
                return ResourceManager.GetString("Text_Change_Status_Lincense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to change your survey status:.
        /// </summary>
        public static string Text_Change_Status_Oprostnik {
            get {
                return ResourceManager.GetString("Text_Change_Status_Oprostnik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the license:.
        /// </summary>
        public static string Text_Delet_License {
            get {
                return ResourceManager.GetString("Text_Delet_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you really want to delete the following question:.
        /// </summary>
        public static string Text_Question_Delet {
            get {
                return ResourceManager.GetString("Text_Question_Delet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill out the form to determine for what period you need statistics.
        /// </summary>
        public static string Text_Statistica_Data {
            get {
                return ResourceManager.GetString("Text_Statistica_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics for the question:.
        /// </summary>
        public static string Text_Statistica_Question {
            get {
                return ResourceManager.GetString("Text_Statistica_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of responses .
        /// </summary>
        public static string Total_number_responses {
            get {
                return ResourceManager.GetString("Total_number_responses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock.
        /// </summary>
        public static string Unlock {
            get {
                return ResourceManager.GetString("Unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update date.
        /// </summary>
        public static string UpdateDate {
            get {
                return ResourceManager.GetString("UpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name not found or incorrect email.
        /// </summary>
        public static string UserNotFoundOrIncorrenctEmailValidation {
            get {
                return ResourceManager.GetString("UserNotFoundOrIncorrenctEmailValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value doesn&apos;t match.
        /// </summary>
        public static string Value_not_match {
            get {
                return ResourceManager.GetString("Value_not_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for response _.
        /// </summary>
        public static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes/No.
        /// </summary>
        public static string YesNo {
            get {
                return ResourceManager.GetString("YesNo", resourceCulture);
            }
        }
    }
}
